baseURL = "https://cooklang.org/"
languageCode = "en-ie"
title = "Cooklang: recipe markup language"
themesDir = "./themes"
theme = "cooklang-tw"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Syntax highlighting configuration
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
    lineNoSeparator = '  '
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true
      xhtml = false
      hardWraps = false
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true
  [markup.goldmark.parser.fencedCodeBlock]
    [markup.goldmark.parser.fencedCodeBlock.syntaxHighlighting]
      [markup.goldmark.parser.fencedCodeBlock.syntaxHighlighting.chroma]
        [markup.goldmark.parser.fencedCodeBlock.syntaxHighlighting.chroma.styles]
          cooklang = "cooklang"
          sh = "sh"
          yaml = "yaml"
          toml = "toml"

# Add supported languages
[markup.highlight.languages]
  cooklang = "cooklang"
  sh = "sh"
  yaml = "yaml"
  toml = "toml"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30
# sectionPagesMenu = "main"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "CLI"
    url = "/cli/"
    weight = 3

[[menu.main]]
    name = "Mobile App"
    url = "/app/"
    weight = 4

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5


[params]
  google_analytics_id="G-5XEMVMR4NG"
  # homepage_button_link = '/docs'
  # homepage_button_text = 'Read The Docs'
  # homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  # homepage_image = '/images/terminal.gif'
  mainSections = ["docs", "cli", "app", "blog"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.author]
    name = "Alexey"
    email = "hello@cooklang.org"

  [params.homepage_meta_tags]
    meta_description = "Cooklang is a markup language for recipes."
    meta_og_title = "Cooklang – Recipe Markup Language"
    meta_og_type = "website"
    meta_og_url = "https://cooklang.org"
    meta_og_image = "https://cooklang.org/example.png"
    meta_og_description = "Cooklang is a markup language for recipes."
    # meta_twitter_card = "summary"
    # meta_twitter_site = "@Cooklang"
    # meta_twitter_creator = "@Cooklang"

  [params.logo]
      mobile = "/logo.svg"
      standard  = "/logo.svg"

[outputFormats]
  [outputFormats.HTML]
    isPlainText = false
    mediaType = "text/html"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
